Portal-1146: Table Pagination
CDCgov/cdc-react pull request #117
Opened 2023-12-18 17:58 UTC by ian-sawyer

- This pr adds pagination to the table component
- Please review locally in storybook

2023-12-18 20:29 UTC, sublettk requested changes

2023-12-18 20:48 UTC, sublettk commented on packages/cdc-react/src/components/Table/TablePagination/TablePagination.scss
> +  margin-top: units(1);
Disregard.

2023-12-18 21:05 UTC, ian-sawyer commented on packages/cdc-react/src/components/Table/TablePagination/TablePagination.scss
> +    padding: units("05");
The ones with "*05" are strings. They only work specifically in quotes.

2023-12-18 21:22 UTC, sublettk requested changes
Let's add some unit tests.

For example, one of the functionalities that stands out to me is ensuring that the calculation of the number of pages leads to a whole number quantity of pages.

2023-12-20 15:37 UTC, sublettk approved these changes

2023-12-20 15:56 UTC, merged