Portal 1514/status tracker component
CDCgov/cdc-react pull request #132
Opened 2024-04-01 20:30 UTC by ZacharyRizer

Related to this ticket: https://cdc-dexops.atlassian.net/browse/PORTAL-1514

* created the `ProgressTracker` component
* design aligned with this figma: https://www.figma.com/file/TrW6WMf6GYgscPkVQaiMZ0/CDC-React-Components?type=design&node-id=1887-4672&mode=design&t=mT0ftvVfPshafIa1-0
* created stories for the component to show the three different variants (inProgress-Determinate, inProgress-Indeterminate, and Complete)
* added tests for the component

2024-04-02 14:31 UTC, sublettk requested changes
Looks good so far. There are some changes that need to be revised regarding the boundaries of the props.

2024-04-02 14:31 UTC, sublettk commented on packages/cdc-react/src/components/ProgressTracker/ProgressTracker.tsx
Observation from Storybook:
- `currentAmount` should maintain a whole number as it increases and decreases
- The value of `currentAmount` should be between 0 and 100.
- `totalAmount` should be between 0 and 100.

2024-04-02 14:41 UTC, ZacharyRizer commented on packages/cdc-react/src/components/ProgressTracker/ProgressTracker.tsx
> +  complete = false,
Yep, good call.

2024-04-02 14:41 UTC, ZacharyRizer commented on packages/cdc-react/src/components/ProgressTracker/ProgressTracker.tsx
> +  indeterminate = false,
Yep, agreed.

2024-04-02 15:15 UTC, ZacharyRizer commented on packages/cdc-react/src/components/ProgressTracker/ProgressTracker.tsx
Adjusted handling of current vs total amount. If current amount exceeds total, current is set to the total and `100%` is returned. Percentage calculations always `floor` to an integer.

2024-04-02 15:16 UTC, ZacharyRizer commented on packages/cdc-react/src/components/ProgressTracker/ProgressTracker.tsx
> +    if (complete) return "Complete";
I decided to leave the `currentAmount` alone in the case of the `isComplete` boolean. If we need to adjust down the line we can, but I don't want to manipulate internal state unless needed. I think having transparency and data consistency is more important here.

2024-04-02 15:17 UTC, ZacharyRizer commented on packages/cdc-react/src/components/ProgressTracker/ProgressTracker.test.tsx
Tests added!

2024-04-02 15:19 UTC, ian-sawyer commented on packages/cdc-react/src/components/ProgressTracker/ProgressTracker.scss
> +  border-radius: 8px;
I think this should be 1rem to align more with the design.

2024-04-02 15:19 UTC, ian-sawyer commented on packages/cdc-react/src/components/ProgressTracker/ProgressTracker.scss
> +  border-radius: 8px;
I think this should be 1rem to align more with the design.

2024-04-02 16:48 UTC, ian-sawyer commented on packages/cdc-react/src/components/ProgressTracker/ProgressTracker.tsx
> +    return Math.floor(percentage);
I think making this `Math.floor(percentage).toFixed(2);` would be best for display purposes.

2024-04-02 17:52 UTC, ian-sawyer commented on packages/cdc-react/src/components/ProgressTracker/ProgressTracker.tsx
> +    return `${getBarPercentage()}% complete`;
A wrapper method to slice the string max to show two decimals would be useful here I think.

2024-04-04 13:09 UTC, ian-sawyer approved these changes
LGTM!

2024-04-04 13:19 UTC, sublettk approved these changes
LGTM!

2024-04-04 13:26 UTC, merged