Portal-1010: Implement opacity for button states
CDCgov/cdc-react pull request #46
Opened 2023-09-20 18:25 UTC by ian-sawyer

- Utilizes Sass mixins to create button hover states based-off opacity
- Adds the color palettes for primary/tertiary button states

2023-09-27 14:56 UTC, cfarmer-fearless requested changes

2023-09-27 14:56 UTC, cfarmer-fearless commented on packages/cdc-react/src/components/Button/Button.test.tsx
> -  it("should execute onClick callback when enter key pressed", () => {
Why remove this test?

2023-09-27 15:13 UTC, ian-sawyer commented on packages/cdc-react/src/components/Button/Button.test.tsx
> -  it("should execute onClick callback when enter key pressed", () => {
Whoops.

2023-10-04 13:25 UTC, cfarmer-fearless requested changes

2023-10-04 13:25 UTC, cfarmer-fearless commented on packages/cdc-react/src/components/Button/Button.tsx
> +    <div
I want to get rid of this button wrap `div`.  I don't think it's necessary and goes against a11y guidelines.  What's the reason for re-introducing it?

2023-10-04 14:41 UTC, cfarmer-fearless approved these changes

2023-10-04 14:46 UTC, merged